name: empSeg_env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - pytorch=2.0.0
  - torchvision=0.15
  - opencv
  - albumentations
  - jupyterlab
  - pip:
    - torchsummary
    - matplotlib==2.0.0


